"""initial schema

Revision ID: 20907b7121db
Revises:
Create Date: 2026-08-11 13:15:05.658078
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20907b7121db"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eval_runs",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("git_sha", sa.String(length=40), nullable=True),
        sa.Column("is_baseline", sa.Boolean(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("per_question", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_runs")),
    )
    op.create_index("ix_eval_runs_name", "eval_runs", ["name", "started_at"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("role", sa.Enum("customer", "agent", "admin", name="user_role"), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("tenant_id", "email", name="uq_users_tenant_email"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "claim_viewed",
                "claim_access_denied",
                "answer_generated",
                "answer_abstained",
                "document_uploaded",
                "document_deleted",
                "login",
                "login_failed",
                name="audit_action",
            ),
            nullable=False,
        ),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=True),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("allowed", sa.Boolean(), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_log_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_actor", "audit_log", ["actor_user_id", "created_at"], unique=False)
    op.create_index("ix_audit_denied", "audit_log", ["allowed", "created_at"], unique=False)
    op.create_index(
        "ix_audit_resource", "audit_log", ["resource_type", "resource_id"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_conversations_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("thread_id", name=op.f("uq_conversations_thread_id")),
    )
    op.create_index(
        op.f("ix_conversations_created_at"), "conversations", ["created_at"], unique=False
    )
    op.create_index(
        "ix_conversations_user", "conversations", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("insurer", sa.String(length=255), nullable=True),
        sa.Column("product_name", sa.String(length=255), nullable=True),
        sa.Column("uin", sa.String(length=64), nullable=True),
        sa.Column(
            "doc_type",
            sa.Enum(
                "policy_wording",
                "endorsement",
                "sop",
                "circular",
                "claim_form",
                "brochure",
                "other",
                name="doc_type",
            ),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("jurisdiction", sa.String(length=64), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_documents_uploaded_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(op.f("ix_documents_created_at"), "documents", ["created_at"], unique=False)
    op.create_index(
        "ix_documents_effective", "documents", ["effective_from", "effective_to"], unique=False
    )
    op.create_index(
        "ix_documents_tenant_product", "documents", ["tenant_id", "product_name"], unique=False
    )
    op.create_table(
        "policy_holders",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("external_ref", sa.String(length=64), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_policy_holders_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_holders")),
        sa.UniqueConstraint("tenant_id", "external_ref", name="uq_policy_holders_tenant_ref"),
        sa.UniqueConstraint("user_id", name=op.f("uq_policy_holders_user_id")),
    )
    op.create_index(
        op.f("ix_policy_holders_created_at"), "policy_holders", ["created_at"], unique=False
    )
    op.create_index("ix_policy_holders_tenant", "policy_holders", ["tenant_id"], unique=False)
    op.create_table(
        "document_versions",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "parsing",
                "chunking",
                "embedding",
                "indexing",
                "completed",
                "failed",
                name="ingestion_status",
            ),
            nullable=False,
        ),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("is_superseded", sa.Boolean(), nullable=False),
        sa.Column("parser", sa.String(length=64), nullable=True),
        sa.Column("chunk_strategy_version", sa.String(length=32), nullable=True),
        sa.Column("embedding_model", sa.String(length=128), nullable=True),
        sa.Column("embedding_dim", sa.Integer(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_versions_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint("content_hash", name="uq_doc_versions_content_hash"),
        sa.UniqueConstraint("document_id", "version_no", name="uq_doc_versions_doc_version"),
    )
    op.create_index("ix_doc_versions_status", "document_versions", ["status"], unique=False)
    op.create_index(
        op.f("ix_document_versions_created_at"), "document_versions", ["created_at"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column(
            "role", sa.Enum("user", "assistant", "system", name="message_role"), nullable=False
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "intent",
            sa.Enum(
                "policy_qa",
                "claim_status",
                "claim_intake",
                "smalltalk",
                "out_of_scope",
                name="intent",
            ),
            nullable=True,
        ),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("retrieved_chunk_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("abstained", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        "ix_messages_conversation", "messages", ["conversation_id", "created_at"], unique=False
    )
    op.create_table(
        "policies",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("policy_number", sa.String(length=64), nullable=False),
        sa.Column("policy_holder_id", sa.UUID(), nullable=False),
        sa.Column("insurer", sa.String(length=255), nullable=False),
        sa.Column("product_name", sa.String(length=255), nullable=False),
        sa.Column("uin", sa.String(length=64), nullable=True),
        sa.Column("sum_insured", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("inception_date", sa.Date(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "lapsed", "cancelled", "expired", name="policy_status"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["policy_holder_id"],
            ["policy_holders.id"],
            name=op.f("fk_policies_policy_holder_id_policy_holders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policies")),
        sa.UniqueConstraint("tenant_id", "policy_number", name="uq_policies_tenant_number"),
    )
    op.create_index(op.f("ix_policies_created_at"), "policies", ["created_at"], unique=False)
    op.create_index("ix_policies_holder", "policies", ["policy_holder_id"], unique=False)
    op.create_index("ix_policies_product", "policies", ["tenant_id", "product_name"], unique=False)
    op.create_table(
        "chunks",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("document_version_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("parent", "child", "table", "table_summary", name="chunk_kind"),
            nullable=False,
        ),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("section_path", sa.String(length=1024), nullable=True),
        sa.Column("page_no", sa.Integer(), nullable=True),
        sa.Column("char_start", sa.Integer(), nullable=True),
        sa.Column("char_end", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedded_text", sa.Text(), nullable=True),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("is_superseded", sa.Boolean(), nullable=False),
        sa.Column("embedding_model", sa.String(length=128), nullable=True),
        sa.Column("chunk_strategy_version", sa.String(length=32), nullable=True),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
            name=op.f("fk_chunks_document_version_id_document_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["chunks.id"],
            name=op.f("fk_chunks_parent_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
    )
    op.create_index("ix_chunks_active", "chunks", ["tenant_id", "is_superseded"], unique=False)
    op.create_index("ix_chunks_document", "chunks", ["document_id"], unique=False)
    op.create_index("ix_chunks_parent", "chunks", ["parent_id"], unique=False)
    op.create_index(
        "ix_chunks_version_index", "chunks", ["document_version_id", "chunk_index"], unique=False
    )
    op.create_table(
        "claims",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("claim_number", sa.String(length=64), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("policy_holder_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "submitted",
                "under_review",
                "info_required",
                "approved",
                "partially_approved",
                "rejected",
                "settled",
                "closed",
                "withdrawn",
                name="claim_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "claim_type",
            sa.Enum("cashless", "reimbursement", "pre_authorization", name="claim_type"),
            nullable=False,
        ),
        sa.Column("date_of_loss", sa.Date(), nullable=False),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("approved_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("settled_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("rejection_reason_code", sa.String(length=64), nullable=True),
        sa.Column("rejection_clause_ref", sa.String(length=255), nullable=True),
        sa.Column("hospital_name", sa.String(length=255), nullable=True),
        sa.Column("diagnosis", sa.Text(), nullable=True),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "approved_amount IS NULL OR approved_amount >= 0",
            name=op.f("ck_claims_approved_nonneg"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
            name=op.f("fk_claims_assigned_to_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["policy_holder_id"],
            ["policy_holders.id"],
            name=op.f("fk_claims_policy_holder_id_policy_holders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
            name=op.f("fk_claims_policy_id_policies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claims")),
        sa.UniqueConstraint("tenant_id", "claim_number", name="uq_claims_tenant_number"),
    )
    op.create_index(op.f("ix_claims_created_at"), "claims", ["created_at"], unique=False)
    op.create_index("ix_claims_holder", "claims", ["policy_holder_id"], unique=False)
    op.create_index(
        "ix_claims_owner_lookup",
        "claims",
        ["tenant_id", "claim_number", "policy_holder_id"],
        unique=False,
    )
    op.create_index("ix_claims_status", "claims", ["tenant_id", "status"], unique=False)
    op.create_table(
        "feedback",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("rating", sa.Enum("up", "down", name="feedback_rating"), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("promoted_to_golden", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_feedback_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_feedback_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
        sa.UniqueConstraint("message_id", "user_id", name="uq_feedback_message_user"),
    )
    op.create_table(
        "claim_events",
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "submitted",
                "under_review",
                "info_required",
                "approved",
                "partially_approved",
                "rejected",
                "settled",
                "closed",
                "withdrawn",
                name="claim_status",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "submitted",
                "under_review",
                "info_required",
                "approved",
                "partially_approved",
                "rejected",
                "settled",
                "closed",
                "withdrawn",
                name="claim_status",
            ),
            nullable=True,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("actor", sa.String(length=255), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
            name=op.f("fk_claim_events_claim_id_claims"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim_events")),
    )
    op.create_index(
        "ix_claim_events_claim", "claim_events", ["claim_id", "occurred_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_claim_events_claim", table_name="claim_events")
    op.drop_table("claim_events")
    op.drop_table("feedback")
    op.drop_index("ix_claims_status", table_name="claims")
    op.drop_index("ix_claims_owner_lookup", table_name="claims")
    op.drop_index("ix_claims_holder", table_name="claims")
    op.drop_index(op.f("ix_claims_created_at"), table_name="claims")
    op.drop_table("claims")
    op.drop_index("ix_chunks_version_index", table_name="chunks")
    op.drop_index("ix_chunks_parent", table_name="chunks")
    op.drop_index("ix_chunks_document", table_name="chunks")
    op.drop_index("ix_chunks_active", table_name="chunks")
    op.drop_table("chunks")
    op.drop_index("ix_policies_product", table_name="policies")
    op.drop_index("ix_policies_holder", table_name="policies")
    op.drop_index(op.f("ix_policies_created_at"), table_name="policies")
    op.drop_table("policies")
    op.drop_index("ix_messages_conversation", table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_document_versions_created_at"), table_name="document_versions")
    op.drop_index("ix_doc_versions_status", table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_index("ix_policy_holders_tenant", table_name="policy_holders")
    op.drop_index(op.f("ix_policy_holders_created_at"), table_name="policy_holders")
    op.drop_table("policy_holders")
    op.drop_index("ix_documents_tenant_product", table_name="documents")
    op.drop_index("ix_documents_effective", table_name="documents")
    op.drop_index(op.f("ix_documents_created_at"), table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_conversations_user", table_name="conversations")
    op.drop_index(op.f("ix_conversations_created_at"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("ix_audit_resource", table_name="audit_log")
    op.drop_index("ix_audit_denied", table_name="audit_log")
    op.drop_index("ix_audit_actor", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_eval_runs_name", table_name="eval_runs")
    op.drop_table("eval_runs")
    # ### end Alembic commands ###
